name: Haskell CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Haskell
        uses: haskell-actions/setup@v1
        with:
          ghc-version: '9.2.5'
          cabal-version: '3.6.2.0'
          stack-version: 'latest'

      - name: Install dependencies
        run: |
          cabal update
          cabal build --only-dependencies --enable-tests

      - name: Build project
        run: |
          cabal build --enable-tests

      - name: Run tests
        run: |
          cabal test --test-show-details=streaming

      - name: Run hlint
        run: |
          cabal install hlint
          hlint .

      - name: Run formatter
        run: |
          cabal install stylish-haskell
          find . -name '*.hs' | xargs stylish-haskell -i

      - name: Verify formatting
        run: |
          cabal install ormolu
          ormolu --mode check $(find . -name '*.hs')
